Update README.md
stat6250-s17/course-questions-wiki pull request #199
Opened 2017-05-24 06:10 UTC by cyuan10-stat6250

Quiz 9

2017-05-24 16:17 UTC, prof-lankham requested changes
All contributions should begin with "- Question" or "- Answer", with a hyphen (-) followed by a space. Please update this PR to match this convention.

2017-05-25 14:45 UTC, prof-lankham commented on week-09/README.md
> +[Course Textbook Chapter 14, Problem 2]
Contributions should be inserted under existing headers, alongside exist content. Please do not create your own headers.

2017-05-25 14:45 UTC, prof-lankham commented on week-09/README.md
> +
Please remove extraneous line breaks from your contributions.

2017-05-25 14:46 UTC, prof-lankham commented on week-09/README.md
> +=======
Contributions should only be questions or answers, not formatting elements like separators.

2017-05-25 14:46 UTC, prof-lankham commented on week-09/README.md
> +- Question
All contributions should follow the specified formatting conventions.

2017-05-25 14:49 UTC, prof-lankham requested changes
Please resolve the formatting issues discussed in the embedded comments. The suggested workflow for this process is as follows: (1) Update the master branch of your fork of this repo; (2) create a new branch for the Week 9 Quiz; and (3) copy/paste your properly formatted contributions so they're added at the end of each collection of questions/answers for each Quiz Problem.

2017-05-25 23:41 UTC, cyuan10-stat6250 commented
Updated v2.

2017-05-25 23:51 UTC, merged