Update README.md
stat6250-s17/course-questions-wiki pull request #36
Opened 2017-04-04 22:28 UTC by yzhu12-stat6250

2017-04-04 23:12 UTC, prof-lankham commented on week-02/README.md
> +- Question (yzhu12-stat6250): In a SAS table, what does the rows and columns represent?
This block of changes all appear at the top of the file, rather than interspersed under the supplied headers; please update to remove redundant headers and move questions/answers under supplied headers.

2017-04-04 23:13 UTC, prof-lankham requested changes
Please update PR so that all content appears in designated areas.

2017-04-04 23:16 UTC, prof-lankham commented on week-02/README.md
> +[loading_data_from_remote_Excel_file SAS Recipe (from Week 2 Overview)]
This question appears to be about the advanced version of the recipe, rather than the basic version; please move this under the "advanced" header and add a question about the basic version of the recipe.

2017-04-05 00:21 UTC, yzhu12-stat6250 commented
I have fix the error. Thank you!

2017-04-05 00:38 UTC, prof-lankham commented on week-02/README.md
> +- Question (yzhu12-stat6250): In a SAS table, what does the rows and columns represent?
Rather than create new headers for each problem in Chapter 1, please interlace your questions within existing content so that only a single header appears for each quiz problem.

2017-04-05 00:39 UTC, prof-lankham requested changes
Please address both comments, including interlacing your questions for Chapter 1 Problems into existing content, and adding a new question for the basic recipe for loading data from a remote Excel file.

2017-04-06 01:10 UTC, prof-lankham requested changes
Please address the comment added at the end of your proposed changed before this PR can be accepted.

2017-04-06 01:10 UTC, prof-lankham commented on week-02/README.md
> +- Question (yzhu12-stat6250): What's the meaning of two command % and & in SAS?
This question is for the "advanced" version of the recipe, not the "basic" version. Please move this question under the header for the "advanced" version of the recipe below, and please add a question for the "basic" version of the recipe (i.e., the version without macros).

2017-04-06 02:29 UTC, merged