Week 2 Submission
stat6250-s17/course-questions-wiki pull request #48
Opened 2017-04-05 06:24 UTC by mcardoso3-stat6250

2017-04-06 03:04 UTC, prof-lankham commented on README.md
> +- Question (mcardoso3~stat6250): How many observations and variables are needed for a large enough sample size to draw a strong conclusion from the data provided?
Throughout, you appear to be using a tilde (~) in your Slack username, rather than a dash (-); please update to use a dash.

2017-04-06 03:04 UTC, prof-lankham requested changes
Please address comments before this PR can be accepted.

2017-04-06 16:31 UTC, mcardoso3-stat6250 commented
Thank you, Quiz 2 has been updated.

2017-04-06 16:41 UTC, prof-lankham requested changes
Your username now appears to be correct throughout. However, it appears that you are editing the README.md file at the root of the repo, rather than week-02/README.md. Please move your contributions to Week 2's README.md file, and please interlace your contributions with existing contributions so the all questions/answers for a give Quiz Problem/SAS Recipe appear under a common header.

2017-04-06 22:31 UTC, mcardoso3-stat6250 commented
Ok, I believe I updated week 2, but I'm not entirely sure.  If not, please let me know.

2017-04-06 22:36 UTC, prof-lankham commented
You can see a summary of all changed in the PR as follows: https://github.com/stat6250/course-questions-wiki/pull/48/files

Note that the file being changed is "README.md", not "week-02/README.md"

2017-04-06 23:35 UTC, prof-lankham commented
Your most recent commit still has edits to the README.md file at the root-level of the repo, rather than the README.md file in the week-02 folder.

Please message me in Slack if it would be helpful to talk through any of the details of submission process.

2017-04-09 21:01 UTC, prof-lankham commented
This is being closed in order to prevent it from becoming stale.

Please message me in Slack to discuss further.

2017-04-09 21:01 UTC, closed without merging